EXPERIMENT:
  NAME: "BCP1_7"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "BCP"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 240
  LR: 0.001
  LR_DECAY_STAGES: []
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0
  MOMENTUM: 0.9
  TYPE: "SGD"
BCP:
  OPTION: 1
  J: 10.0
  K: 0.001
  MSE_K: 0.001