EXPERIMENT:
  NAME: "BCP3_4"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "BCP"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 16
  EPOCHS: 240
  LR: 0.005
  LR_DECAY_STAGES: []
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.000
  MOMENTUM: 0.0
  TYPE: "SGD"
BCP:
  OPTION: 3
  J: 0.5
  K: 0.0001
  MSE_K: 0.0001