EXPERIMENT:
  NAME: "BCPLI10_2"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "BCPLI"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 240
  LR: 0.1
  LR_DECAY_STAGES: [30, 60, 90, 120, 150, 180, 210]
  LR_DECAY_RATE: 0.5
  WEIGHT_DECAY: 0.0
  MOMENTUM: 0.0
  TYPE: "SGD"
BCPLI:
  OPTION: 1
  COLLAPSE_OPTION: 0
  J: 0.5
  K: 0.1
  J_O: 0.5
  K_O: 0.1
