EXPERIMENT:
  NAME: "BD2563"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "BD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 640
  LR: 0.05
  LR_DECAY_STAGES: [250, 400, 500, 600]
  LR_DECAY_RATE: 0.7
  WEIGHT_DECAY: 0.00005
  MOMENTUM: 0.5
  TYPE: "SGD"
