EXPERIMENT:
  NAME: "BD_9_8"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "BD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 440
  LR: 0.05
  LR_DECAY_STAGES: [250, 380, 410]
  LR_DECAY_RATE: 0.5
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.2
  TYPE: "SGD"
