EXPERIMENT:
  NAME: "BDMSE_8"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "BDMSE"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 340
  LR: 0.05
  LR_DECAY_STAGES: [150, 280, 310]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.01
  MOMENTUM: 0.0
  TYPE: "SGD"
BDMSE:
  MSE_WEIGHT: 0.2