EXPERIMENT:
  NAME: "KDS_1"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "KDS"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 20
  EPOCHS: 300
  LR: 0.001
  LR_DECAY_STAGES: [100,120,140,160,180,200,220,240]
  LR_DECAY_RATE: 0.7
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
KDS:
  LOSS:
    CE_WEIGHT: 0.1
    KD_WEIGHT: 0.9
