EXPERIMENT:
  NAME: "SLDE1"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDE"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 10
  EPOCHS: 240
  LR: 0.005
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
SLDE:
  X_WEIGHT: 0.0
  I_WEIGHT: 1.0
  E: 1.05
