EXPERIMENT:
  NAME: "SLDM2_1"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDM"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 10
  EPOCHS: 450
  LR: 0.005
  LR_DECAY_STAGES: [250,300,350,400]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
SLDM:
  X_WEIGHT: 1.0
  I_WEIGHT: 0.0
  M: 10.0
