EXPERIMENT:
  NAME: "SLDMSE_X19"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDMSE"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 350
  LR: 0.004
  LR_DECAY_STAGES: [100, 125, 150, 175, 200, 225, 250, 275, 300, 325]
  LR_DECAY_RATE: 0.5
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  TYPE: "SGD"
SLDMSE:
  MSE_WEIGHT: 0.05
