EXPERIMENT:
  NAME: "SLDMSE_2_3"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDMSE"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.005
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.8
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.8
  TYPE: "SGD"
SLDMSE:
  MSE_WEIGHT: 0.05
