EXPERIMENT:
  NAME: "SLDONLY9_1"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDONLY"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 300
  LR: 0.005
  LR_DECAY_STAGES: [50, 100, 130, 160, 190, 210, 230, 250, 270 ]
  LR_DECAY_RATE: 0.7
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
SLDONLY:
  X_WEIGHT: 0.0
  I_WEIGHT: 1.0
