EXPERIMENT:
  NAME: "SLDONLY3_5"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDONLY"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 500
  LR: 0.01
  LR_DECAY_STAGES: [200, 300, 400, 450]
  LR_DECAY_RATE: 0.5
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
SLDONLY:
  X_WEIGHT: 0.0
  I_WEIGHT: 1.0
