EXPERIMENT:
  NAME: "SLDONLY13_3_4"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDONLY"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 350
  LR: 0.002
  LR_DECAY_STAGES: [ 200, 220, 240, 260, 280, 300]
  LR_DECAY_RATE: 0.4
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
SLDONLY:
  X_WEIGHT: 1.0
  I_WEIGHT: 0.0
