EXPERIMENT:
  NAME: "SLDONLY3_3"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDONLY"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 10
  EPOCHS: 1000
  LR: 0.005
  LR_DECAY_STAGES: [200, 400, 600, 700, 800, 900]
  LR_DECAY_RATE: 0.9
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
SLDONLY:
  X_WEIGHT: 0.0
  I_WEIGHT: 1.0
