EXPERIMENT:
  NAME: "SLDONLY5"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDONLY"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 10
  EPOCHS: 260
  LR: 0.005
  LR_DECAY_STAGES: [20, 40, 60, 80, 100, 140, 180, 220]
  LR_DECAY_RATE: 0.8
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
SLDONLY:
  X_WEIGHT: 0.5
  I_WEIGHT: 0.5
