EXPERIMENT:
  NAME: "SLDONLY8_1"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDONLY"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 20
  EPOCHS: 300
  LR: 0.001
  LR_DECAY_STAGES: [100,120,140,160,180,200,220,240]
  LR_DECAY_RATE: 0.7
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
SLDONLY:
  X_WEIGHT: 0.0
  I_WEIGHT: 1.0
