EXPERIMENT:
  NAME: "SLDR_4346"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDR"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 440
  LR: 0.005
  LR_DECAY_STAGES: [350, 380, 410]
  LR_DECAY_RATE: 0.8
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.2
  TYPE: "SGD"
SLDR:
  X_WEIGHT: 0.0
  I_WEIGHT: 1.0
  MSE_PROB: 0.1
  MSE_WEIGHT: 10.0
