EXPERIMENT:
  NAME: "SLDR_7_1"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDR"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.008
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.7
  TYPE: "SGD"
SLDR:
  X_WEIGHT: 0.0
  I_WEIGHT: 1.0
  MSE_PROB: 0.2
  MSE_WEIGHT: 5.0
