EXPERIMENT:
  NAME: "SLDR_632"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDR"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 300
  LR: 0.002
  LR_DECAY_STAGES: [100, 120, 140, 160, 180, 200, 220, 240, 260]
  LR_DECAY_RATE: 0.9
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  TYPE: "SGD"
SLDR:
  X_WEIGHT: 0.0
  I_WEIGHT: 1.0
  MSE_PROB: 0.2
  MSE_WEIGHT: 40.0
