EXPERIMENT:
  NAME: "IN_MIX_II_R34_R18_3_11_0_5_4"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 3
DISTILLER:
  TYPE: "MIX_II"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 15
  LR: 0.01
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  TYPE: "SGD"
MIX_II:
  BD_WEIGHT: 10.0
  MACD_WEIGHT: 0.8
