EXPERIMENT:
  NAME: "MIX_III_19"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DATASET:
  NUM_WORKERS: 3
DISTILLER:
  TYPE: "MIX_III"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 340
  LR: 0.002
  LR_DECAY_STAGES: [250, 280, 310]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  TYPE: "SGD"
MIX_III:
  B_WEIGHT: 0.5
  C_WEIGHT: 0.3
  B_AXIS: 2
  C_AXIS: 0