EXPERIMENT:
  NAME: "MIX_VI_MAX_6"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DATASET:
  NUM_WORKERS: 3
DISTILLER:
  TYPE: "MIX_VI_MAX"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 16
  EPOCHS: 340
  LR: 0.0005
  LR_DECAY_STAGES: [250, 280, 310]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  TYPE: "SGD"
MIX_VI_MAX:
  BD_WEIGHT: 20.0
  CDA_WEIGHT: 1.0
  CDB_WEIGHT: 1.0
  MSE_WEIGHT: 0.1
  B_WEIGHT: 2.0
  C_WEIGHT: 0.5
  LOSSES_R: 4