#!/bin/bash
qsub -N "dg_59" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_0.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_0.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_0.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_60" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_1.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_1.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_1.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_61" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_2.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_2.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_2.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_62" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_3.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_3.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_3.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_63" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_4.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_4.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_4.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_64" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_5.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_5.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_5.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_65" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_6.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_6.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_6.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_66" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_7.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_7.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_7.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_67" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_8.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_8.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_mix_i/MIX_I_3_3_8.out" /projectnb/textconv/distill/scripts/submit10hr.sh