#!/bin/bash
qsub -N "dg_16_1" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/imagenet/_sldmse/r50mnv1/SLDMSE_r50mnv1_1.yaml" -e "/projectnb/textconv/distill/test16_1.err" -o "/projectnb/textconv/distill/test16_1.out" /projectnb/textconv/distill/scripts/submit10hr_16w_1.sh
qsub -N "dg_16_2" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/imagenet/_sldmse/r50mnv1/SLDMSE_r50mnv1_1.yaml" -e "/projectnb/textconv/distill/test16_2.err" -o "/projectnb/textconv/distill/test16_2.out" /projectnb/textconv/distill/scripts/submit10hr_16w_2.sh
qsub -N "dg_16_3" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/imagenet/_sldmse/r50mnv1/SLDMSE_r50mnv1_1.yaml" -e "/projectnb/textconv/distill/test16_3.err" -o "/projectnb/textconv/distill/test16_3.out" /projectnb/textconv/distill/scripts/submit10hr_16w_3.sh
qsub -N "dg_16_4" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/imagenet/_sldmse/r50mnv1/SLDMSE_r50mnv1_1.yaml" -e "/projectnb/textconv/distill/test16_4.err" -o "/projectnb/textconv/distill/test16_4.out" /projectnb/textconv/distill/scripts/submit10hr_16w_4.shqsub -N "dg_0" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_0.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_0.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_0.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_1" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_1.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_1.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_1.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_2" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_2.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_2.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_2.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_3" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_3.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_3.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_3.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_4" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_4.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_4.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_4.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_5" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_5.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_5.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_5.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_6" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_6.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_6.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_6.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_7" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_7.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_7.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_7.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_8" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_8.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_8.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_8.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_9" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_9.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_9.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_9.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_10" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_10.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_10.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_10.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_11" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_11.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_11.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_11.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_12" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_12.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_12.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_12.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_13" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_13.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_13.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_13.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_14" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_14.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_14.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_14.out" /projectnb/textconv/distill/scripts/submit10hr.sh
qsub -N "dg_15" -v CONFIG="/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_15.yaml" -e "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_15.err" -o "/projectnb/textconv/distill/mdistiller/configs/cifar100/_sldmse/r56r20/SLDMSEAVG_1_15.out" /projectnb/textconv/distill/scripts/submit10hr.sh
