EXPERIMENT:
  NAME: "MIX_I_0"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DATASET:
  NUM_WORKERS: 3
DISTILLER:
  TYPE: "MIX_I"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 440
  LR: 0.004
  LR_DECAY_STAGES: [350, 380, 410]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  TYPE: "SGD"
MIX_I:
  MSE_WEIGHT: 0.5
  MACD_WEIGHT: 0.1
