EXPERIMENT:
  NAME: "MACDP32_1"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DATASET:
  NUM_WORKERS: 3
DISTILLER:
  TYPE: "MACDP"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 340
  LR: 0.002
  LR_DECAY_STAGES: [350, 380, 410]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  TYPE: "SGD"