EXPERIMENT:
  NAME: "1SLDMSE_T4_0_4"
  TAG: "kd,res50,mobilenetv1"
  PROJECT: "imagenet_sldmse"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 10
  TEST:
    BATCH_SIZE: 64
DISTILLER:
  TYPE: "SLDMSEAVG"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.005
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  TYPE: "SGD"
SLDMSEAVG:
  MSE_WEIGHT: 0.5



