EXPERIMENT:
  NAME: "SLDMSECHAIN_GRADACC_1"
  TAG: "kd,res50,mobilenetv1"
  PROJECT: "imagenet_sldmse"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 8
  TEST:
    BATCH_SIZE: 64
DISTILLER:
  TYPE: "SLDMSEAVG"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  LR: 0.00001
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  TYPE: "SGD"
  GRAD_ACC:
    ACC_BATCHES: 20
SLDMSEAVG:
  MSE_WEIGHT: 0.001



