EXPERIMENT:
  NAME: "BLDMSE_R328R84_ACC_7_13_2"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DATASET:
  NUM_WORKERS: 3
DISTILLER:
  TYPE: "BLDMSE"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 340
  LR: 0.001
  LR_DECAY_STAGES: [250, 280, 310]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.05
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "grad_acc"
  GRAD_ACC: 
    ACC_BATCHES: 50
BLDMSE:
  MSE_WEIGHT: 1.0
