EXPERIMENT:
  NAME: "BLDMSE_R328R84_BATCH_20"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "BLDMSE"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 11
  EPOCHS: 200
  LR: 0.005
  LR_DECAY_STAGES: [100, 130, 160]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.05
  MOMENTUM: 0.9
  TYPE: "SGD"
BLDMSE:
  MSE_WEIGHT: 0.0