EXPERIMENT:
  NAME: "TIN_MIX_II_MN2_1_0_11"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "tiny_imagenet_baselines"
DATASET:
  TYPE: "tiny_imagenet"
  NUM_WORKERS: 3
DISTILLER:
  TYPE: "MIX_II"
  TEACHER: "ResNet18"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 150
  LR: 0.005
  LR_DECAY_STAGES: [100, 200, 300]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  TYPE: "SGD"
MIX_II:
  BD_WEIGHT: 1.0
  MACD_WEIGHT: 0.5