EXPERIMENT:
  NAME: "MIX_II_OTHER_18_6"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DATASET:
  NUM_WORKERS: 3
DISTILLER:
  TYPE: "MIX_II"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 16
  EPOCHS: 340
  LR: 0.001
  LR_DECAY_STAGES: [250, 280, 310]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: -0.005
  MOMENTUM: 0.9
  TYPE: "SGD"
MIX_II:
  BD_WEIGHT: 10.0
  MACD_WEIGHT: 2.0
