EXPERIMENT:
  NAME: "MACDPL_9"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DATASET:
  NUM_WORKERS: 3
DISTILLER:
  TYPE: "MACDPL"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 440
  LR: 0.002
  LR_DECAY_STAGES: [350, 380, 410]
  LR_DECAY_RATE: 0.5
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  TYPE: "SGD"
MACDPL:
  CE_WEIGHT: 0.8
