EXPERIMENT:
  NAME: "SLDMSE_R56R20XDS1_11"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDMSE"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 340
  LR: 0.003
  LR_DECAY_STAGES: [250, 280, 310]
  LR_DECAY_RATE: 0.2
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  TYPE: "SGD"
SLDMSE:
  MSE_WEIGHT: 0.04
