EXPERIMENT:
  NAME: "SLDMSE_R56R20X_2_5_7"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDMSE"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.003
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.2
  WEIGHT_DECAY: 0.05
  MOMENTUM: 0.9
  TYPE: "SGD"
SLDMSE:
  MSE_WEIGHT: 0.01
