EXPERIMENT:
  NAME: "SLDMSE_R56R20GRADACC_0"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SLDMSE"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 440
  LR: 0.001
  LR_DECAY_STAGES: [350, 380, 410]
  LR_DECAY_RATE: 0.2
  WEIGHT_DECAY: 0.005
  MOMENTUM: 0.9
  TYPE: "SGD"
  GRAD_ACC:
    ACC_BATCHES: 20
SLDMSE:
  MSE_WEIGHT: 0.008
