EXPERIMENT:
  NAME: "BLDCD2P_13L2_2"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DATASET:
  NUM_WORKERS: 3
DISTILLER:
  TYPE: "BLDCD2P"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 540
  LR: 0.0005
  LR_DECAY_STAGES: [450, 480, 510]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.05
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "grad_acc"
  GRAD_ACC: 
    ACC_BATCHES: 50