EXPERIMENT:
  NAME: "BLDCD2P_14L2_6"
  TAG: "sld,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DATASET:
  NUM_WORKERS: 3
DISTILLER:
  TYPE: "BLDCD2P"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 540
  LR: 0.002
  LR_DECAY_STAGES: [450, 480, 510]
  LR_DECAY_RATE: 0.5
  WEIGHT_DECAY: 0.05
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "grad_acc"
  GRAD_ACC: 
    ACC_BATCHES: 100